services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 'senhaderootmariadb'
      MARIADB_DATABASE: 'glpi'
      MARIADB_USER: 'glpi'
      MARIADB_PASSWORD: 'senhadousuarioglpi'
    volumes:
    - mariadb:/var/lib/mysql
    ports:
    - "3306:3306"

  glpi:
    image: aprendendolinux/glpi-alpine
    restart: always
    depends_on:
      - mariadb
    links:
      - "mariadb:mariadb"
    container_name: glpi
    environment:
      TIMEZONE: "America/Sao_Paulo"
      VERSION: 10.0.17
      UPLOAD_MAX_FILESIZE: 100M
      POST_MAX_FILESIZE: 50M
    volumes:
      - glpi:/var/www/localhost/htdocs
    ports:
      - "80:80"
volumes:
  mariadb:
  glpi:
